extends Control
## Generated by the SpawnWeaver editor plugin — Room Chat starter.
## Auto-connects using the credentials saved in the SpawnWeaver dock.

var _log: RichTextLabel
var _msg: LineEdit
var _code: LineEdit


func _ready() -> void:
	_build_ui()
	MultiplayerService.welcomed.connect(func(_id): _line("Connected. Create or join a room."))
	MultiplayerService.connection_error.connect(func(r): _line("Error: " + r))
	MultiplayerService.room_created.connect(func(_id, code, _p): _line("Room code: " + code))
	MultiplayerService.room_joined.connect(_on_room_joined)
	MultiplayerService.event_received.connect(_on_event)
	if not MultiplayerService.connect_using_config():
		_line("No saved config — set credentials in the SpawnWeaver editor dock.")


func _build_ui() -> void:
	set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	var root := VBoxContainer.new()
	root.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	add_child(root)

	var row := HBoxContainer.new()
	var create := Button.new(); create.text = "Create Room"
	create.pressed.connect(func(): MultiplayerService.create_room("Me"))
	row.add_child(create)
	_code = LineEdit.new(); _code.placeholder_text = "Room code"
	row.add_child(_code)
	var join := Button.new(); join.text = "Join"
	join.pressed.connect(func(): MultiplayerService.join_room(_code.text.strip_edges().to_upper(), "Me"))
	row.add_child(join)
	root.add_child(row)

	_log = RichTextLabel.new(); _log.size_flags_vertical = Control.SIZE_EXPAND_FILL
	root.add_child(_log)

	var send_row := HBoxContainer.new()
	_msg = LineEdit.new(); _msg.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_msg.text_submitted.connect(func(_t): _send())
	send_row.add_child(_msg)
	var send := Button.new(); send.text = "Send"; send.pressed.connect(_send)
	send_row.add_child(send)
	root.add_child(send_row)


func _send() -> void:
	var text := _msg.text.strip_edges()
	if text == "":
		return
	MultiplayerService.send_event("chat", {"name": "Me", "text": text})
	_line("Me: " + text)
	_msg.clear()


func _on_room_joined(_id: String, _code: String, _player: Dictionary, _players: Array) -> void:
	_line("Joined room.")


func _on_event(event: String, data: Dictionary, _from: String) -> void:
	if event == "chat":
		_line("%s: %s" % [str(data.get("name", "?")), str(data.get("text", ""))])


func _line(text: String) -> void:
	_log.add_text(text + "\n")
