extends Control
## Generated by the SpawnWeaver editor plugin — Lobby starter.
## Auto-connects using the credentials saved in the SpawnWeaver dock.

var _log: RichTextLabel
var _code: LineEdit


func _ready() -> void:
	_build_ui()
	MultiplayerService.welcomed.connect(func(_id): _line("Connected. Create or join a lobby."))
	MultiplayerService.connection_error.connect(func(r): _line("Error: " + r))
	MultiplayerService.lobby_created.connect(func(lobby): _line("Lobby code: " + str(lobby.get("code", lobby.get("roomCode", "")))))
	MultiplayerService.lobby_list.connect(_on_lobby_list)
	MultiplayerService.lobby_joined.connect(func(_id, _p, players): _line("Joined lobby (%d players)." % players.size()))
	MultiplayerService.player_joined.connect(func(_r, p): _line("Player joined: " + str(p.get("playerId", ""))))
	if not MultiplayerService.connect_using_config():
		_line("No saved config — set credentials in the SpawnWeaver editor dock.")


func _build_ui() -> void:
	set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	var root := VBoxContainer.new()
	root.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	add_child(root)

	var row := HBoxContainer.new()
	var create := Button.new(); create.text = "Create Lobby"
	create.pressed.connect(func(): MultiplayerService.create_lobby("My Lobby", "public", 8, {}, "Me"))
	row.add_child(create)
	var list := Button.new(); list.text = "List Lobbies"
	list.pressed.connect(func(): MultiplayerService.list_lobbies())
	row.add_child(list)
	_code = LineEdit.new(); _code.placeholder_text = "Lobby code"
	row.add_child(_code)
	var join := Button.new(); join.text = "Join"
	join.pressed.connect(func(): MultiplayerService.join_lobby(_code.text.strip_edges().to_upper(), "Me"))
	row.add_child(join)
	root.add_child(row)

	_log = RichTextLabel.new(); _log.size_flags_vertical = Control.SIZE_EXPAND_FILL
	root.add_child(_log)


func _on_lobby_list(lobbies: Array) -> void:
	if lobbies.is_empty():
		_line("No public lobbies.")
	for lobby in lobbies:
		_line("Lobby %s — %d player(s)" % [str(lobby.get("name", "")), int(lobby.get("playerCount", 0))])


func _line(text: String) -> void:
	_log.add_text(text + "\n")
