extends Control
## Generated by the SpawnWeaver editor plugin — Matchmaking starter.
## Auto-connects using the credentials saved in the SpawnWeaver dock.

var _status: Label
var _find: Button


func _ready() -> void:
	_build_ui()
	MultiplayerService.welcomed.connect(func(_id): _status_text("Connected. Click Find Match."))
	MultiplayerService.connection_error.connect(func(r): _status_text("Error: " + r))
	MultiplayerService.matchmaking_queued.connect(func(_m, _r, _s): _status_text("Searching for an opponent…"))
	MultiplayerService.match_found.connect(_on_match_found)
	MultiplayerService.matchmaking_timeout.connect(func(_m, _r): _on_ready_again("No opponent found — try again."))
	MultiplayerService.event_received.connect(func(ev, data, from): if ev == "move": _status_text("Opponent %s moved: %s" % [from, str(data)]))
	if not MultiplayerService.connect_using_config():
		_status_text("No saved config — set credentials in the SpawnWeaver editor dock.")


func _build_ui() -> void:
	set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	var root := VBoxContainer.new()
	root.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	add_child(root)

	_find = Button.new(); _find.text = "Find Match"; _find.disabled = false
	_find.pressed.connect(func(): MultiplayerService.join_matchmaking("duel_1v1", "global", 2, "Me"); _find.disabled = true)
	root.add_child(_find)

	_status = Label.new(); _status.text = "Connecting…"
	root.add_child(_status)


func _on_match_found(_room_id: String, room_code: String, players: Array) -> void:
	_status_text("Match found! Room %s with %d players. Send a move:" % [room_code, players.size()])
	MultiplayerService.send_event("move", {"x": 10, "y": 5})


func _on_ready_again(message: String) -> void:
	_find.disabled = false
	_status_text(message)


func _status_text(text: String) -> void:
	_status.text = text
