extends Node2D
## Generated by the SpawnWeaver editor plugin — Starter Game.
##
## A complete, minimal multiplayer game you can play in under a minute: enter a name, create or
## join a room by code, then move with the arrow keys and watch the other players move in real
## time. It auto-connects to SpawnWeaver using the credentials saved in the editor dock, so there
## are no keys or URLs to paste in code. Use it as the foundation for your own game.
##
## Try it with two players: Debug → Run Multiple Instances (set 2+), run this scene, create a room
## in one window and join it by code in the other.

const SPEED := 220.0
const SEND_INTERVAL := 0.05    # seconds between position updates (≈20/s)

var _status: Label
var _name_edit: LineEdit
var _code_edit: LineEdit

var _in_room := false
var _my_id := ""
var _my_pos := Vector2(320, 240)
var _players: Dictionary = {}        # player_id -> { pos: Vector2, name: String }
var _send_accum := 0.0


func _ready() -> void:
	_build_ui()

	MultiplayerService.welcomed.connect(func(_id): _set_status("Connected. Enter a name, then Create or Join a room."))
	MultiplayerService.connection_error.connect(func(reason): _set_status("Connection error: " + reason))
	MultiplayerService.sdk_error.connect(func(e): _set_status("Error: " + str(e.get("message", ""))))
	MultiplayerService.room_created.connect(func(_id, code, _p): _set_status("Room ready — share code: " + code); _enter())
	MultiplayerService.room_joined.connect(_on_room_joined)
	MultiplayerService.player_left.connect(func(_room, pid): _players.erase(pid))
	MultiplayerService.state_snapshot_received.connect(_on_snapshot)
	MultiplayerService.entity_state_changed.connect(_on_entity_changed)
	MultiplayerService.entity_state_deleted.connect(func(id): _players.erase(id))

	if not MultiplayerService.connect_using_config():
		_set_status("No saved config — open the SpawnWeaver dock and Save your public key first.")


func _process(delta: float) -> void:
	if not _in_room:
		return
	var move := Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	if move != Vector2.ZERO:
		_my_pos += move * SPEED * delta
		_my_pos = _my_pos.clamp(Vector2(16, 64), Vector2(624, 464))
		_send_accum += delta
		if _send_accum >= SEND_INTERVAL:
			_send_accum = 0.0
			# Our position is shared as entity state keyed by our player id; everyone else
			# receives it via entity_state_changed and draws us.
			MultiplayerService.patch_entity_state(_my_id, {"x": _my_pos.x, "y": _my_pos.y})
	queue_redraw()


func _draw() -> void:
	for pid in _players:
		var p: Dictionary = _players[pid]
		var pos: Vector2 = p.get("pos", Vector2.ZERO)
		var is_me: bool = pid == _my_id
		draw_circle(pos, 16.0, Color(0.2, 0.75, 1.0) if is_me else Color(1.0, 0.55, 0.25))
		var label := str(p.get("name", "Player"))
		draw_string(ThemeDB.fallback_font, pos + Vector2(-20, -22), label, HORIZONTAL_ALIGNMENT_LEFT, -1, 13)


# --- UI ---

func _build_ui() -> void:
	var row := HBoxContainer.new(); row.position = Vector2(8, 8)
	add_child(row)

	_name_edit = LineEdit.new(); _name_edit.placeholder_text = "Your name"; _name_edit.text = "Player"
	_name_edit.custom_minimum_size = Vector2(110, 0)
	row.add_child(_name_edit)

	var create := Button.new(); create.text = "Create Room"
	create.pressed.connect(func(): MultiplayerService.create_room(_player_name()))
	row.add_child(create)

	_code_edit = LineEdit.new(); _code_edit.placeholder_text = "Room code"; _code_edit.custom_minimum_size = Vector2(110, 0)
	row.add_child(_code_edit)

	var join := Button.new(); join.text = "Join"
	join.pressed.connect(func(): MultiplayerService.join_room(_code_edit.text.strip_edges().to_upper(), _player_name()))
	row.add_child(join)

	_status = Label.new(); _status.position = Vector2(8, 40)
	add_child(_status)
	_set_status("Connecting…")


func _player_name() -> String:
	var n := _name_edit.text.strip_edges()
	return n if n != "" else "Player"


# --- Room + state ---

func _on_room_joined(_room_id: String, code: String, player: Dictionary, _players_list: Array) -> void:
	if str(player.get("playerId", "")) == MultiplayerService.player_id:
		if code != "":
			_set_status("Joined room " + code + " — move with the arrow keys.")
		_enter()


func _enter() -> void:
	_in_room = true
	_my_id = MultiplayerService.player_id
	_my_pos = Vector2(120 + randi() % 360, 120 + randi() % 240)
	_players[_my_id] = {"pos": _my_pos, "name": _player_name()}
	# Publish our starting position + name so others can draw us immediately.
	MultiplayerService.set_entity_state(_my_id, {"x": _my_pos.x, "y": _my_pos.y, "name": _player_name()})


func _on_snapshot(snapshot: Dictionary) -> void:
	for e in snapshot.get("entities", []):
		_apply_entity(str(e.get("entityId", "")), e.get("state", {}))


func _on_entity_changed(entity_id: String, _patch: Dictionary, full_state: Dictionary) -> void:
	_apply_entity(entity_id, full_state)


func _apply_entity(entity_id: String, state: Dictionary) -> void:
	if entity_id == "":
		return
	var existing: Dictionary = _players.get(entity_id, {})
	_players[entity_id] = {
		"pos": Vector2(float(state.get("x", 0)), float(state.get("y", 0))),
		"name": str(state.get("name", existing.get("name", "Player"))),
	}


func _set_status(text: String) -> void:
	if _status != null:
		_status.text = text
