extends Node2D
## Generated by the SpawnWeaver editor plugin — State Sync Player starter.
## Auto-connects using the credentials saved in the SpawnWeaver dock.

const SPEED := 200.0

var _status: Label
var _code: LineEdit
var _in_room := false
var _my_id := ""
var _my_pos := Vector2(320, 240)
var _entities: Dictionary = {}     # entity_id -> Vector2
var _accum := 0.0


func _ready() -> void:
	_build_ui()
	MultiplayerService.welcomed.connect(func(_id): _status_text("Connected. Create or join a room."))
	MultiplayerService.connection_error.connect(func(r): _status_text("Error: " + r))
	MultiplayerService.room_created.connect(func(_id, code, _p): _status_text("Room code: " + code); _enter())
	MultiplayerService.room_joined.connect(_on_room_joined)
	MultiplayerService.state_snapshot_received.connect(_on_snapshot)
	MultiplayerService.entity_state_changed.connect(func(id, _patch, full): _entities[id] = Vector2(float(full.get("x", 0)), float(full.get("y", 0))))
	MultiplayerService.entity_state_deleted.connect(func(id): _entities.erase(id))
	if not MultiplayerService.connect_using_config():
		_status_text("No saved config — set credentials in the SpawnWeaver editor dock.")


func _process(delta: float) -> void:
	if _in_room:
		var move := Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
		if move != Vector2.ZERO:
			_my_pos += move * SPEED * delta
			_accum += delta
			if _accum >= 0.06:
				_accum = 0.0
				MultiplayerService.patch_entity_state(_my_id, {"x": _my_pos.x, "y": _my_pos.y})
	queue_redraw()


func _draw() -> void:
	for id in _entities:
		var color := Color(0.2, 0.75, 1.0) if id == _my_id else Color(1.0, 0.55, 0.25)
		draw_circle(_entities[id], 14.0, color)


func _build_ui() -> void:
	var row := HBoxContainer.new(); row.position = Vector2(8, 8)
	add_child(row)
	var create := Button.new(); create.text = "Create Room"
	create.pressed.connect(func(): MultiplayerService.create_room("Me"))
	row.add_child(create)
	_code = LineEdit.new(); _code.placeholder_text = "Room code"; _code.custom_minimum_size = Vector2(110, 0)
	row.add_child(_code)
	var join := Button.new(); join.text = "Join"
	join.pressed.connect(func(): MultiplayerService.join_room(_code.text.strip_edges().to_upper(), "Me"))
	row.add_child(join)
	_status = Label.new(); _status.position = Vector2(8, 40)
	add_child(_status)


func _on_room_joined(_id: String, _code: String, player: Dictionary, _players: Array) -> void:
	if str(player.get("playerId", "")) == MultiplayerService.player_id:
		_enter()


func _enter() -> void:
	_in_room = true
	_my_id = MultiplayerService.player_id
	_my_pos = Vector2(120 + randi() % 200, 240)
	MultiplayerService.set_entity_state(_my_id, {"x": _my_pos.x, "y": _my_pos.y})
	_status_text("In room — move with the arrow keys.")


func _on_snapshot(snapshot: Dictionary) -> void:
	for e in snapshot.get("entities", []):
		var s: Dictionary = e.get("state", {})
		_entities[str(e.get("entityId", ""))] = Vector2(float(s.get("x", 0)), float(s.get("y", 0)))


func _status_text(text: String) -> void:
	_status.text = text
